# Generated by Django 4.2.23 on 2025-08-29 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, help_text='مثال: 05XXXXXXXX', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'رقم الجوال يجب أن يبدأ بـ 0 ويتكون من 10 أرقام')], verbose_name='رقم الجوال')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الهوية يجب أن يتكون من 10 أرقام')], verbose_name='رقم الهوية')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعلم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف (وصول للوحة الإدارة)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم (معلم)',
                'verbose_name_plural': 'المستخدمون (المعلمين)',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='العنوان / البرنامج')),
                ('report_date', models.DateField(db_index=True, verbose_name='تاريخ التقرير / البرنامج')),
                ('day_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='اليوم')),
                ('beneficiaries_count', models.PositiveIntegerField(blank=True, help_text='اتركه فارغًا إذا لا ينطبق', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد المستفيدين')),
                ('idea', models.TextField(blank=True, null=True, verbose_name='الوصف / فكرة التقرير')),
                ('category', models.CharField(choices=[('activity', 'نشاط'), ('volunteer', 'تطوع'), ('school_affairs', 'مسؤول الشؤون المدرسية '), ('admin', 'إدارية'), ('evidence', 'شواهد')], db_index=True, default='school_affairs', max_length=32, verbose_name='التصنيف')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='reports_rep_categor_f39dbe_idx'), models.Index(fields=['teacher', 'category'], name='reports_rep_teacher_d39fd4_idx'), models.Index(fields=['report_date'], name='reports_rep_report__cd5337_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone'], name='reports_tea_phone_e31005_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['national_id'], name='reports_tea_nationa_c2a1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='reports_tea_name_a50ea3_idx'),
        ),
    ]
