# Generated by Django 5.2.5 on 2025-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_teacher_is_admin_alter_teacher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
