# Generated by Django 4.2.23 on 2025-09-02 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_create_report_table_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='يُحفظ هنا الاسم الظاهر في التقرير بغض النظر عن تغيّر اسم الحساب لاحقًا.', max_length=120, verbose_name='اسم المعلم (وقت الإنشاء)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('activity', 'نشاط'), ('volunteer', 'تطوع'), ('school_affairs', 'شؤون مدرسية'), ('admin', 'إدارية'), ('evidence', 'شواهد')], db_index=True, max_length=32, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المعلم (حساب)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('teacher', 'المعلم'), ('manager', 'مدير'), ('activity_officer', 'مسؤول النشاط'), ('volunteer_officer', 'مسؤول التطوع'), ('affairs_officer', 'مسؤول الشؤون المدرسية'), ('admin_officer', 'مسؤول الشؤون الإدارية')], default='teacher', max_length=32),
        ),
    ]
