# Generated by Django 4.2.23 on 2025-08-26 12:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_teacher_is_admin_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreport',
            name='date',
        ),
        migrations.AddField(
            model_name='activityreport',
            name='day_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='اليوم'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2025, 8, 26), verbose_name='تاريخ البرنامج'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المعلم'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الهوية يجب أن يكون 10 أرقام فقط')], verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'رقم الجوال يجب أن يبدأ بـ 0 ويتكون من 10 أرقام')], verbose_name='رقم الجوال'),
        ),
    ]
