# Generated by Django 5.1.7 on 2025-09-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_role_can_view_all_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='reporttypes',
            field=models.ManyToManyField(blank=True, help_text='اختَر الأنواع التي يحق لمسؤولي هذا القسم الاطلاع عليها (تُزامَن تلقائيًا مع دور القسم).', related_name='departments', to='reports.reporttype', verbose_name='أنواع التقارير المرتبطة'),
        ),
        migrations.AlterField(
            model_name='department',
            name='role_label',
            field=models.CharField(blank=True, help_text='هذا الاسم سيظهر كخيار (دور) عند إضافة المعلّم. إن تُرك فارغًا سيُستخدم اسم القسم.', max_length=120, verbose_name='الاسم الظاهر في قائمة (الدور)'),
        ),
    ]
