# Generated by Django 4.2.23 on 2025-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_merge_20250902_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('teacher', 'المعلم'), ('manager', 'مدير'), ('activity_officer', 'مسؤول النشاط'), ('volunteer_officer', 'مسؤول التطوع'), ('affairs_officer', 'مسؤول الشؤون المدرسية'), ('admin_officer', 'مسؤول الشؤون الإدارية')], default='teacher', max_length=32),
        ),
    ]
