# Generated by Django 4.2.23 on 2025-09-27 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import reports.storage


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_notification_notificationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='يسمح بـ PDF/صور/DOCX حتى 5MB', null=True, storage=reports.storage.PublicRawMediaStorage(), upload_to='tickets/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), reports.models.validate_attachment_size], verbose_name='مرفق'),
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.ticket', verbose_name='التذكرة')),
            ],
            options={
                'verbose_name': 'صورة تذكرة',
                'verbose_name_plural': 'صور التذكرة',
                'ordering': ['id'],
            },
        ),
    ]
