# Generated by Django 4.2.23 on 2025-09-02 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_teacher_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('manager', 'المدير'), ('activity_officer', 'مسؤول النشاط'), ('volunteer_officer', 'مسؤول التطوع'), ('affairs_officer', 'مسؤول الشؤون المدرسية'), ('admin_officer', 'مسؤول الشؤون الإدارية')], db_index=True, max_length=32, verbose_name='القسم/الجهة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الطلب')),
                ('body', models.TextField(verbose_name='تفاصيل الطلب')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='مرفق (اختياري)')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'تم الإنجاز'), ('rejected', 'مرفوض')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'تم الإنجاز'), ('rejected', 'مرفوض')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'تم الإنجاز'), ('rejected', 'مرفوض')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.requestticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requestticket',
            index=models.Index(fields=['department', 'status'], name='reports_req_departm_aa1920_idx'),
        ),
        migrations.AddIndex(
            model_name='requestticket',
            index=models.Index(fields=['assignee', 'status'], name='reports_req_assigne_14186d_idx'),
        ),
    ]
