# Generated by Django 4.2.23 on 2025-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_ticket_attachment_ticketimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimage',
            name='image',
            field=models.ImageField(upload_to='tickets/images/%Y/%m/%d/', verbose_name='الصورة'),
        ),
    ]
