# Generated by Django 4.2.23 on 2025-09-02 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_requestticket_requestlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('admin_officer', 'الشؤون الإدارية'), ('affairs_officer', 'الشؤون المدرسية'), ('activity_officer', 'النشاط'), ('volunteer_officer', 'التطوع')], db_index=True, max_length=32, verbose_name='القسم')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الطلب')),
                ('body', models.TextField(blank=True, null=True, verbose_name='تفاصيل الطلب')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('status', models.CharField(choices=[('open', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'مكتمل'), ('rejected', 'مرفوض')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='الملاحظة')),
                ('is_public', models.BooleanField(default=True, verbose_name='ظاهرة للمرسل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reports.ticket')),
            ],
            options={
                'verbose_name': 'ملاحظة طلب',
                'verbose_name_plural': 'ملاحظات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status', 'created_at'], name='reports_tic_departm_9c3a70_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'status'], name='reports_tic_assigne_9effbd_idx'),
        ),
    ]
