# Generated by Django 4.2.23 on 2025-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_ticket_ticketnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('admin_officer', 'الشؤون الإدارية'), ('affairs_officer', 'الشؤون المدرسية'), ('activity_officer', 'النشاط'), ('volunteer_officer', 'التطوع'), ('manager', 'المدير'), ('teacher', 'المعلمين')], db_index=True, max_length=32, verbose_name='القسم'),
        ),
    ]
