# Generated by Django 4.2.23 on 2025-09-04 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_ticket_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرّف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل طلب (تراثي)', 'verbose_name_plural': 'سجل الطلبات (تراثي)'},
        ),
        migrations.AlterModelOptions(
            name='requestticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب (تراثي)', 'verbose_name_plural': 'طلبات (تراثية)'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مستخدم (معلم)', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منفّذ العملية'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'تم الإنجاز'), ('rejected', 'مرفوض')], max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('done', 'تم الإنجاز'), ('rejected', 'مرفوض')], max_length=20, verbose_name='الحالة القديمة'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.requestticket', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='requestticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='requestticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='موظّف لوحة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الهوية الوطنية'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('teacher', 'المعلم'), ('manager', 'مدير'), ('activity_officer', 'مسؤول النشاط'), ('volunteer_officer', 'مسؤول التطوع'), ('affairs_officer', 'مسؤول الشؤون المدرسية'), ('admin_officer', 'مسؤول الشؤون الإدارية')], default='teacher', max_length=32, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to=settings.AUTH_USER_MODEL, verbose_name='كاتب الملاحظة'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reports.ticket', verbose_name='التذكرة'),
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('teacher', 'Teacher'), ('officer', 'Officer')], default='teacher', max_length=16, verbose_name='نوع التكليف')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='reports.department', verbose_name='القسم')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تكليف قسم',
                'verbose_name_plural': 'تكليفات الأقسام',
                'indexes': [models.Index(fields=['department'], name='reports_dep_departm_3627f4_idx'), models.Index(fields=['teacher'], name='reports_dep_teacher_ac8b99_idx')],
                'unique_together': {('department', 'teacher')},
            },
        ),
    ]
