# Generated by Django 4.2.23 on 2025-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_department_alter_requestlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AddField(
            model_name='department',
            name='role_label',
            field=models.CharField(blank=True, help_text='الاسم الذي سيظهر في قائمة (الدور). إن تُرك فارغًا سيُستخدم اسم القسم.', max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
